### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by ydubreuil**
Add two 2 API calls required for our internal tooling to:

* Retrieve currently authenticated user
* Search Help Center articles belonging to a section

### CODE REVIEW

**Comment by christ66** [comment]
:bee:

**Comment by ydubreuil** [comment]
@reviewbybees

**Comment by alecharp** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by ydubreuil** [comment]
@reviewbybees done

**Pull request merged**
