### PR TITLE
Custom Agent Roles

### PR DESCRIPTION
**Pull request by matthewtckr**

### CODE REVIEW

**Comment by matthewtckr** [comment]
Can someone test this with an account that doesn't have Custom Roles and/or a non-Enterprise account that is not entitled to Custom Roles?

The API documentation is unclear about what type of exception (if any) will be thrown in these cases, and may cause a test case failure in those instances.

**Comment by stephenc** [comment]
needs rebase.

If you can clarify what tests are needed to be checked, I have a test account from ZenDesk and I can run the test

**Comment by matthewtckr** [comment]
@stephenc I've run the `RealSmokeTest.getCustomAgentRoles()` on an enterprise account, but I don't know how that API might react on a standard Zendesk account which doesn't support Custom Agent Roles.  As long as it doesn't throw an Exception, I'd say 👍

**Comment by stephenc** [comment]
```
$ mvn clean test -Dtest=RealSmokeTest\#getCustomAgentRoles
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building zendesk-java-client 0.5.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6:clean (default-clean) @ zendesk-java-client ---
[INFO] Deleting /Users/stephenc/src/zendesk-java-client/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ zendesk-java-client ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ zendesk-java-client ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ zendesk-java-client ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 82 source files to /Users/stephenc/src/zendesk-java-client/target/classes
[WARNING] /Users/stephenc/src/zendesk-java-client/src/main/java/org/zendesk/client/v2/Zendesk.java: /Users/stephenc/src/zendesk-java-client/src/main/java/org/zendesk/client/v2/Zendesk.java uses unchecked or unsafe operations.
[WARNING] /Users/stephenc/src/zendesk-java-client/src/main/java/org/zendesk/client/v2/Zendesk.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ zendesk-java-client ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ zendesk-java-client ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /Users/stephenc/src/zendesk-java-client/target/test-classes
[WARNING] /Users/stephenc/src/zendesk-java-client/src/test/java/org/zendesk/client/v2/RealSmokeTest.java: /Users/stephenc/src/zendesk-java-client/src/test/java/org/zendesk/client/v2/RealSmokeTest.java uses unchecked or unsafe operations.
[WARNING] /Users/stephenc/src/zendesk-java-client/src/test/java/org/zendesk/client/v2/RealSmokeTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ zendesk-java-client ---
[INFO] Surefire report directory: /Users/stephenc/src/zendesk-java-client/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.zendesk.client.v2.RealSmokeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.69 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.119 s
[INFO] Finished at: 2016-10-05T14:42:01+01:00
[INFO] Final Memory: 17M/212M
[INFO] ------------------------------------------------------------------------
```

**Comment by stephenc** [comment]
Does this mean we can put a check mark in the Readme against Custom Agent Roles?

**Comment by matthewtckr** [comment]
Their API documentation only has a "List Custom Roles" endpoint, which is implemented here.  There is a checkmark in the README as part of this PR, so I think it's ready to commit.

**Comment by stephenc** [comment]
@matthewtckr go for it so

**Pull request merged**
