### PR TITLE
[fix #213] Upgrade Java requirement to 1.8 + Verify JDK API compat (Animal Sniffer) + Enforce bytecode max version

### LINKED ISSUE #213: 2018: Do we still need to target Java 1.5 ?
https://github.com/cloudbees/zendesk-java-client/blob/64468af36c2e2e19aae516995bfcfd6670c79987/pom.xml#L136

@stephenc ?

### PR DESCRIPTION
**Pull request by aheritier**
@johnou @stephenc as you will see in few minutes in CI:

```
[INFO] Restricted to JDK 1.7 yet org.asynchttpclient:netty-codec-dns:jar:2.0.38:compile contains io/netty/channel/socket/InternetProtocolFamily2.class targeted to JDK 1.8
[INFO] Restricted to JDK 1.7 yet org.asynchttpclient:async-http-client:jar:2.0.38:compile contains org/asynchttpclient/BoundRequestBuilder.class targeted to JDK 1.8
[INFO] Restricted to JDK 1.7 yet org.asynchttpclient:netty-resolver-dns:jar:2.0.38:compile contains io/netty/channel/ReflectiveChannelFactory.class targeted to JDK 1.8
[INFO] Restricted to JDK 1.7 yet org.asynchttpclient:async-http-client-netty-utils:jar:2.0.38:compile contains org/asynchttpclient/netty/util/ByteBufUtils.class targeted to JDK 1.8
[INFO] Restricted to JDK 1.7 yet org.asynchttpclient:netty-resolver:jar:2.0.38:compile contains io/netty/resolver/AbstractAddressResolver.class targeted to JDK 1.8
```

We cannot target Java 7 with the current deps we have

### CODE REVIEW

**Comment by johnou** [comment]
Iirc we can, Netty uses runtime detection to load / enable specific features.

**Comment by johnou** [comment]
asynchttpclient on the other hand.. I'll check tomorrow morning.

**Comment by aheritier** [comment]
I let you verify @johnou I don't have the knowledge on this (and I'm writing apps with modern JDK :-P ). Not urgent

**Comment by aheritier** [comment]
What a mess. Without taking care of the J7 incompatibility the Netty 4.0 / 4.1 incompatibility is a mess. I have in my app a case similar to https://github.com/netty/netty/issues/6722
In my app I'm using [MockServer](http://www.mock-server.com/) in my tests which depends on Netty 4.1 while our zendesk-java-client uses async-http-client which depends on Netty 4.0

```
[INFO] +- com.cloudbees.thirdparty:zendesk-java-client:jar:0.6.0-SNAPSHOT:compile
[INFO] |  \- org.asynchttpclient:async-http-client:jar:2.0.38:compile
[INFO] |     +- org.asynchttpclient:async-http-client-netty-utils:jar:2.0.38:compile
[INFO] |     |  \- io.netty:netty-buffer:jar:4.1.17.Final:compile
[INFO] |     |     \- (io.netty:netty-common:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.17.Final:compile
[INFO] |     |  +- io.netty:netty-codec:jar:4.1.17.Final:compile
[INFO] |     |  |  \- (io.netty:netty-transport:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     |  \- (io.netty:netty-handler:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-handler:jar:4.1.17.Final:compile
[INFO] |     |  +- (io.netty:netty-buffer:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     |  +- io.netty:netty-transport:jar:4.1.17.Final:compile
[INFO] |     |  |  \- (io.netty:netty-buffer:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     |  \- (io.netty:netty-codec:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.0.54.Final:compile
[INFO] |     |  +- io.netty:netty-common:jar:4.1.17.Final:compile
[INFO] |     |  +- (io.netty:netty-buffer:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     |  \- (io.netty:netty-transport:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     +- org.asynchttpclient:netty-resolver-dns:jar:2.0.38:compile
[INFO] |     |  +- org.asynchttpclient:netty-resolver:jar:2.0.38:compile
[INFO] |     |  |  \- (io.netty:netty-common:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     |  +- org.asynchttpclient:netty-codec-dns:jar:2.0.38:compile
[INFO] |     |  |  \- (io.netty:netty-codec:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     |  \- (io.netty:netty-transport:jar:4.0.54.Final:compile - omitted for duplicate)
[INFO] |     \- com.typesafe.netty:netty-reactive-streams:jar:1.0.8:compile
[INFO] |        \- (io.netty:netty-handler:jar:4.0.41.Final:compile - omitted for conflict with 4.1.17.Final)
[INFO] \- org.mock-server:mockserver-netty:jar:5.2.3:test
[INFO]    +- org.mock-server:mockserver-core:jar:5.2.3:test
[INFO]    |  +- (io.netty:netty-buffer:jar:4.1.17.Final:compile - scope updated from test; omitted for duplicate)
[INFO]    |  +- (io.netty:netty-codec:jar:4.1.17.Final:compile - scope updated from test; omitted for duplicate)
[INFO]    |  +- (io.netty:netty-codec-http:jar:4.1.17.Final:test - omitted for conflict with 4.1.17.Final)
[INFO]    |  +- io.netty:netty-codec-socks:jar:4.1.17.Final:test
[INFO]    |  |  \- (io.netty:netty-codec:jar:4.1.17.Final:test - omitted for duplicate)
[INFO]    |  +- (io.netty:netty-handler:jar:4.1.17.Final:test - omitted for conflict with 4.1.17.Final)
[INFO]    |  \- (io.netty:netty-transport:jar:4.1.17.Final:compile - scope updated from test; omitted for duplicate)
[INFO]    +- (io.netty:netty-buffer:jar:4.1.17.Final:compile - scope updated from test; omitted for duplicate)
[INFO]    +- (io.netty:netty-codec:jar:4.1.17.Final:compile - scope updated from test; omitted for duplicate)
[INFO]    +- (io.netty:netty-codec-http:jar:4.1.17.Final:compile - scope updated from test; omitted for duplicate)
[INFO]    +- (io.netty:netty-common:jar:4.1.17.Final:compile - scope updated from test; omitted for duplicate)
[INFO]    +- (io.netty:netty-handler:jar:4.1.17.Final:compile - scope updated from test; omitted for duplicate)
[INFO]    \- (io.netty:netty-transport:jar:4.1.17.Final:compile - scope updated from test; omitted for duplicate)
```
Thus I have a mix of 4.0/4.1 which is broken

```
[INFO]    io.netty:netty-buffer:jar:4.1.17.Final:compile
[INFO]    io.netty:netty-codec-http:jar:4.1.17.Final:compile
[INFO]    io.netty:netty-codec-socks:jar:4.1.17.Final:test
[INFO]    io.netty:netty-codec:jar:4.1.17.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.17.Final:compile
[INFO]    io.netty:netty-handler:jar:4.1.17.Final:compile
[INFO]    io.netty:netty-resolver:jar:4.1.17.Final:compile
[INFO]    io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.0.54.Final:compile
[INFO]    io.netty:netty-transport:jar:4.1.17.Final:compile
```

The only solution is to upgrade async-http-client in version 2.1.x to have both both frameworks using Netty 4.1 or to downgrade MockServer to use Netty 4.0 everywhere

The joy of transitive dependencies conflicts with incompatible libraries

**Comment by aheritier** [comment]
@slandelle there were some versions of asynchttpclient compatible with Java 7 cc @johnou

**Comment by slandelle** [comment]
@aheritier No, I've dropped Java 7 support a long time ago (needed Java 8's CHM#computeIfAbsent and such). We're in 2018, mate!

**Comment by aheritier** [comment]
I was expecting such response @slandelle Thx
@johnou @stephenc let's target J8 ?

**Comment by johnou** [comment]
@aheritier sgtm

**Comment by aheritier** [comment]
ok lets go @johnou 
It's good @slandelle we will move to 2018 :-)

**Comment by aheritier** [comment]
Should be good @johnou

**Pull request closed without merging**
