### PR TITLE
Added support for multiple organizations for a user - currently in BETA

### PR DESCRIPTION
**Pull request by pliljenberg**
Would be nice to be able to use this Zendesk client with the upcoming support for multiple organization that is currently in BETA.
I could host the code myself but it would be nice to be able to get it from a released version :)

https://support.zendesk.com/hc/communities/public/posts/203464106-Managing-Organization-Memberships-via-the-Zendesk-API

This replaces pull request #29

### CODE REVIEW

**Comment by johnou** [comment]
Waiting for response from Zendesk https://support.zendesk.com/hc/communities/public/posts/203464106-Managing-Organization-Memberships-via-the-Zendesk-API

**Comment by johnou** [comment]
Hi Johno,

My name is James, and I am from the Tier 2 support team. I will be working with you on this ticket now. We do not yet have any date set for when this will be GA. If you are interested in the feature, I'd recommend you sign up with the following form - https://zendesk.wufoo.com/forms/multiple-organizations/

Sincerely,
James Peterson

**Comment by johnou** [comment]
I'll leave this one to @stephenc, he seemed against the idea of pulling in BETA features.

**Comment by stephenc** [comment]
Do we know if they took this feature out of beta? @aheritier @pliljenberg ?

Needs a rebase if we want to merge (i.e. if they took it out of beta)

**Comment by pliljenberg** [comment]
Looks like it's part of the "non-essential" plans at least.
https://support.zendesk.com/hc/en-us/articles/203661976-Creating-managing-and-using-organizations

**Comment by stephenc** [comment]
@pliljenberg then let's go for it. Are you game to rebase your PR?

**Comment by pliljenberg** [comment]
Ill take a look this evening :)

**Pull request merged**
