### PR TITLE
Implement additional Event types

### PR DESCRIPTION
**Pull request by matthewtckr**
Issue #24

### CODE REVIEW

**Comment by matthewtckr** [comment]
The additional Event types were found in analyzing my organization's Ticket Audits, and we currently have a Zendesk Support case open to get these items publicly documented.

**Comment by matthewtckr** [comment]
@reviewbybees 

There's little doc on how to get this merged, let me know if there's a more-appropriate method than this.

Thanks,

**Comment by stephenc** [comment]
I just prefer to see the api documented before merging to master and releasing, but if you can share a public ticket where these event types are discussed that may suffice (depends on what's on the other end of the link)

**Comment by kzantow** [comment]
@matthewtckr agree with @stephenc - perhaps, at least add a brief class-level comment what the types are used for, if possible?

**Comment by matthewtckr** [comment]
Will do.  Waiting on the final publish from Zendesk, and I will update the pull request.  Thank you

**Comment by matthewtckr** [comment]
Updated the classes with Javadoc, including links to the Zendesk documentation that is now available for all three event types included.

**Pull request merged**
