### PR TITLE
HelpCenter Add paging for large resultset

### PR DESCRIPTION
**Pull request by matthewtckr**

### CODE REVIEW

**Comment by ydubreuil** [comment]
I'm worried it will break backward compatibility.

We could merge it in 0.4 with other breaking changes. WDYT @stephenc @aheritier ? I'm gonna create a 0.4 milestone to track these breaking changes if that works for you.

**Comment by stephenc** [comment]
@ydubreuil I think we should be ready to bump to 0.4 now... if you think a release is needed first we can discuss

**Comment by ydubreuil** [comment]
I've merged few non breaking PR, so we can release a last 0.3 version, but I'm not sure it really makes sense. I can bump master to 0.4 and merges remaining PR

**Comment by ydubreuil** [comment]
@matthewtckr merged all PR targeting 0.4, will need to do some tests before releasing

**Pull request merged**
