### PR TITLE
Fixes #130 and #131.

### LINKED ISSUE #130: createUserIdentity should return Identity
```java
public void createUserIdentity
```

should be

```java
public Identity createUserIdentity
```

to match all the other creation methods (and to make it easier to get the id of the created identity).

### PR DESCRIPTION
**Pull request by kflorence**
- Method createUserIdentity should return Identity, not void.
- Add support for updating user identities.

### CODE REVIEW

**Comment by kflorence** [comment]
@stephenc are you the only person with write access to this repo? What kind of ETA can we expect on pull requests? I don't mean to bug, just wondering for planning purposes.

**Comment by kflorence** [comment]
@reviewbybees would be nice to land this soon. let me know if i can do anything to make that happen faster.

**Comment by stephenc** [comment]
@johnou is a non-cloudbees collaborator who has proven trustworthy enough to grant with write access to merge. 

Also @aheritier and @ydubreuil have write access

**Comment by stephenc** [comment]
Looks good to me

**Comment by kflorence** [comment]
@stephenc Thanks!

**Pull request merged**
