### PR TITLE
Added support for tags in Zendesk

### PR DESCRIPTION
**Pull request by pvanassen**
Per request. Coding was done by @kjepper. I just did the pull request.

### CODE REVIEW

**Comment by stephenc** [comment]
Still seems to have line endings borked

**Comment by pvanassen** [comment]
Hmm indeed. Give me a minute.

**Comment by pvanassen** [comment]
I just tried to update my fork from upstream and it seems all line endings have changed from Unix to Windows. 

What I will do is clean up my fork, and re-implement the changes.

**Comment by pvanassen** [comment]
Created new pull request with cleaned up code: https://github.com/cloudbees/zendesk-java-client/pull/31

**Pull request closed without merging**
