### PR TITLE
html_body support for ticket comments

### PR DESCRIPTION
**Pull request by ortemij**
https://developer.zendesk.com/rest_api/docs/core/ticket_comments

### CODE REVIEW

**Comment by gvh1234** [comment]
See pull request #164

**Comment by ortemij** [comment]
@gvh1234 It was created half a year ago, does it really have chances to be merged?
I could add getter for plain_text into mine as well.

**Comment by gvh1234** [comment]
You are right of course, it's painful that we are now hacking around the process to try and keep this project updated.

**Comment by ortemij** [comment]
@stephenc @aheritier @ydubreuil 
Excuse me for inviting you here directly.
Is there any regulations about merging pull-requests for this repo and publishing new versions of the client? As I see there is a lot of pull-requests proposed long time ago without any replies. :(

**Comment by ortemij** [comment]
@johnou Thanks a lot for merging this! When is the next version bulid expexted?

**Comment by johnou** [comment]
@ortemij we'll need to poke @stephenc I don't think I have access to upload releases.

**Comment by ortemij** [comment]
@stephenc @johnou sorry, but what's the status of the next build?

**Comment by aheritier** [comment]
Hi @johnou @ortemij 

I'm working to provide a public CI environment (+ PR validations) for this. 
I will try to have it online before the end of august (after my holidays)
For the release, we are few to be able to do them (because we need an account on oss.sonatype.org...) But @johnou want to have this king of permissions we can see with @stephenc @ydubreuil and others to give him
For now, just ping us if you want a release from master, it's quick to be done

**Comment by ortemij** [comment]
@aheritier Thanks, yes, I would like to release from master now, is it possible?

**Comment by ortemij** [comment]
@aheritier ping...

**Comment by johnou** [comment]
@ortemij stephenc is trying to run integration tests but his "trial" has expired.

**Comment by ortemij** [comment]
And what you suppose to do now?

**Comment by johnou** [comment]
@ortemij stephenc is waiting for Zendesk customer service to get back to him, after they fix up his test environment he will cut a release if the integration (smoke) tests pass.

**Comment by stephenc** [comment]
Still waiting...

screen shot 2017-08-04 at 11 19 14

**Comment by ortemij** [comment]
Still no answer?

**Comment by stephenc** [comment]
Still no answer :-(

**Comment by ortemij** [comment]
And now?

**Pull request merged**
