### PR TITLE
Topic types are lowecased

### PR DESCRIPTION
**Pull request by sudpaw**
Reference: https://developer.zendesk.com/rest_api/docs/web-portal/forums

### CODE REVIEW

**Comment by johnou** [comment]
@sudpaw broken link? I tried finding it myself but I couldn't find any references to topic apart from https://developer.zendesk.com/rest_api/docs/help_center/topics ..

**Comment by matthewtckr** [comment]
It looks like they're fully removing the Web Portal / Forums implementation, and moved everyone over to Help Center.

https://support.zendesk.com/hc/en-us/articles/207323377

**Comment by johnou** [comment]
@matthewtckr thanks! "no longer be able to access your Web portal beginning on November 1, 2016." guess we need to cleanup some endpoints / classes.. @sudpaw have you migrated to Help Center?

**Comment by sudpaw** [comment]
ohx all for the info. Sorry for the late response.

**Pull request closed without merging**
